name: Wealth Gum
favicon: null
layout_spectrum: 0.77773
typography_spectrum: 0.74453
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbf9ee'
    - '#949592'
    - '#b5b6b0'
    - '#555555'
    - '#2a2a2a'
  brandStrength: 0.125
  lightness: 0.1207749885506928
  saturation: 0.9128993272315711
  rhythmicContrast: 0.22829638421535492
purpose: []
